/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubRouteImport } from './routes/_sub'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as SubCartIndexRouteImport } from './routes/_sub/cart/index'
import { Route as LayoutProductIndexRouteImport } from './routes/_layout/product/index'
import { Route as LayoutMeIndexRouteImport } from './routes/_layout/me/index'
import { Route as LayoutFeedbackIndexRouteImport } from './routes/_layout/feedback/index'
import { Route as LayoutAboutIndexRouteImport } from './routes/_layout/about/index'
import { Route as SubProductProductIdRouteImport } from './routes/_sub/product/$productId'
import { Route as SubMeEditUserInfoRouteImport } from './routes/_sub/me/editUserInfo'
import { Route as SubFeedbackAddFeedbackRouteImport } from './routes/_sub/feedback/addFeedback'
import { Route as SubFeedbackFeedbackIdRouteImport } from './routes/_sub/feedback/$feedbackId'

const SubRoute = SubRouteImport.update({
  id: '/_sub',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SubCartIndexRoute = SubCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => SubRoute,
} as any)
const LayoutProductIndexRoute = LayoutProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMeIndexRoute = LayoutMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFeedbackIndexRoute = LayoutFeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutIndexRoute = LayoutAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => LayoutRoute,
} as any)
const SubProductProductIdRoute = SubProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => SubRoute,
} as any)
const SubMeEditUserInfoRoute = SubMeEditUserInfoRouteImport.update({
  id: '/me/editUserInfo',
  path: '/me/editUserInfo',
  getParentRoute: () => SubRoute,
} as any)
const SubFeedbackAddFeedbackRoute = SubFeedbackAddFeedbackRouteImport.update({
  id: '/feedback/addFeedback',
  path: '/feedback/addFeedback',
  getParentRoute: () => SubRoute,
} as any)
const SubFeedbackFeedbackIdRoute = SubFeedbackFeedbackIdRouteImport.update({
  id: '/feedback/$feedbackId',
  path: '/feedback/$feedbackId',
  getParentRoute: () => SubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof LayoutIndexRoute
  '/feedback/$feedbackId': typeof SubFeedbackFeedbackIdRoute
  '/feedback/addFeedback': typeof SubFeedbackAddFeedbackRoute
  '/me/editUserInfo': typeof SubMeEditUserInfoRoute
  '/product/$productId': typeof SubProductProductIdRoute
  '/about': typeof LayoutAboutIndexRoute
  '/feedback': typeof LayoutFeedbackIndexRoute
  '/me': typeof LayoutMeIndexRoute
  '/product': typeof LayoutProductIndexRoute
  '/cart': typeof SubCartIndexRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof LayoutIndexRoute
  '/feedback/$feedbackId': typeof SubFeedbackFeedbackIdRoute
  '/feedback/addFeedback': typeof SubFeedbackAddFeedbackRoute
  '/me/editUserInfo': typeof SubMeEditUserInfoRoute
  '/product/$productId': typeof SubProductProductIdRoute
  '/about': typeof LayoutAboutIndexRoute
  '/feedback': typeof LayoutFeedbackIndexRoute
  '/me': typeof LayoutMeIndexRoute
  '/product': typeof LayoutProductIndexRoute
  '/cart': typeof SubCartIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_sub': typeof SubRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_sub/feedback/$feedbackId': typeof SubFeedbackFeedbackIdRoute
  '/_sub/feedback/addFeedback': typeof SubFeedbackAddFeedbackRoute
  '/_sub/me/editUserInfo': typeof SubMeEditUserInfoRoute
  '/_sub/product/$productId': typeof SubProductProductIdRoute
  '/_layout/about/': typeof LayoutAboutIndexRoute
  '/_layout/feedback/': typeof LayoutFeedbackIndexRoute
  '/_layout/me/': typeof LayoutMeIndexRoute
  '/_layout/product/': typeof LayoutProductIndexRoute
  '/_sub/cart/': typeof SubCartIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/login'
    | '/'
    | '/feedback/$feedbackId'
    | '/feedback/addFeedback'
    | '/me/editUserInfo'
    | '/product/$productId'
    | '/about'
    | '/feedback'
    | '/me'
    | '/product'
    | '/cart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/login'
    | '/'
    | '/feedback/$feedbackId'
    | '/feedback/addFeedback'
    | '/me/editUserInfo'
    | '/product/$productId'
    | '/about'
    | '/feedback'
    | '/me'
    | '/product'
    | '/cart'
  id:
    | '__root__'
    | '/_layout'
    | '/_sub'
    | '/auth/login'
    | '/_layout/'
    | '/_sub/feedback/$feedbackId'
    | '/_sub/feedback/addFeedback'
    | '/_sub/me/editUserInfo'
    | '/_sub/product/$productId'
    | '/_layout/about/'
    | '/_layout/feedback/'
    | '/_layout/me/'
    | '/_layout/product/'
    | '/_sub/cart/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  SubRoute: typeof SubRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sub': {
      id: '/_sub'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sub/cart/': {
      id: '/_sub/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof SubCartIndexRouteImport
      parentRoute: typeof SubRoute
    }
    '/_layout/product/': {
      id: '/_layout/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof LayoutProductIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/me/': {
      id: '/_layout/me/'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof LayoutMeIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/feedback/': {
      id: '/_layout/feedback/'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof LayoutFeedbackIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about/': {
      id: '/_layout/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_sub/product/$productId': {
      id: '/_sub/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof SubProductProductIdRouteImport
      parentRoute: typeof SubRoute
    }
    '/_sub/me/editUserInfo': {
      id: '/_sub/me/editUserInfo'
      path: '/me/editUserInfo'
      fullPath: '/me/editUserInfo'
      preLoaderRoute: typeof SubMeEditUserInfoRouteImport
      parentRoute: typeof SubRoute
    }
    '/_sub/feedback/addFeedback': {
      id: '/_sub/feedback/addFeedback'
      path: '/feedback/addFeedback'
      fullPath: '/feedback/addFeedback'
      preLoaderRoute: typeof SubFeedbackAddFeedbackRouteImport
      parentRoute: typeof SubRoute
    }
    '/_sub/feedback/$feedbackId': {
      id: '/_sub/feedback/$feedbackId'
      path: '/feedback/$feedbackId'
      fullPath: '/feedback/$feedbackId'
      preLoaderRoute: typeof SubFeedbackFeedbackIdRouteImport
      parentRoute: typeof SubRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAboutIndexRoute: typeof LayoutAboutIndexRoute
  LayoutFeedbackIndexRoute: typeof LayoutFeedbackIndexRoute
  LayoutMeIndexRoute: typeof LayoutMeIndexRoute
  LayoutProductIndexRoute: typeof LayoutProductIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAboutIndexRoute: LayoutAboutIndexRoute,
  LayoutFeedbackIndexRoute: LayoutFeedbackIndexRoute,
  LayoutMeIndexRoute: LayoutMeIndexRoute,
  LayoutProductIndexRoute: LayoutProductIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface SubRouteChildren {
  SubFeedbackFeedbackIdRoute: typeof SubFeedbackFeedbackIdRoute
  SubFeedbackAddFeedbackRoute: typeof SubFeedbackAddFeedbackRoute
  SubMeEditUserInfoRoute: typeof SubMeEditUserInfoRoute
  SubProductProductIdRoute: typeof SubProductProductIdRoute
  SubCartIndexRoute: typeof SubCartIndexRoute
}

const SubRouteChildren: SubRouteChildren = {
  SubFeedbackFeedbackIdRoute: SubFeedbackFeedbackIdRoute,
  SubFeedbackAddFeedbackRoute: SubFeedbackAddFeedbackRoute,
  SubMeEditUserInfoRoute: SubMeEditUserInfoRoute,
  SubProductProductIdRoute: SubProductProductIdRoute,
  SubCartIndexRoute: SubCartIndexRoute,
}

const SubRouteWithChildren = SubRoute._addFileChildren(SubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  SubRoute: SubRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
